version: "3.8"

services:
  app:
    container_name: dhaniram_brar_assignment11
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 7775:3000
